OOP school library: decorate a class
Elijahdre/School-Library pull request #2
Opened 2022-11-03 14:17 UTC by Elijahdre

In this PR, I have:
- Create a class `Nameable`.
   - Implement a method called `correct_name` that will raise a `NotImplementedError`.

#### Turn your Person class to Nameable
- Make sure that your Person class inherits from Nameable
- Make sure that this class has a method `correct_name` implemented. It should simply return the name attribute.

#### Prepare base Decorator
- Make sure that it inherits from Nameable.
- In the constructor assign a nameable object from params to an instance variable.
- Implement the `correct_name` method that returns the result of the correct_name method of the `@nameable`.

#### Prepare CapitalizeDecorator and TrimmerDecorator
- For the CapitalizeDecorator:
    - Create a class that inherits from the base Decorator class.
    - Implement a method `correct_name` that capitalizes the output of `@nameable.correct_name`.
- For the TrimmerDecorator:
    - Create a class that inherits from the base Decorator class.
    - Implement a method `correct_name` that makes sure that the output of `@nameable.correct_name` has a maximum of 10 characters. If it's longer it should trim the word.

2022-11-03 15:04 UTC, DeliceLydia requested changes
## Hi @Elijahdre, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!




### Cheers!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

2022-11-03 15:04 UTC, DeliceLydia commented on decorators/trimmer_decorator.rb
> +  end
- [ ] I am getting an error when I run the app that comes from this class:
![Screenshot from 2022-11-03 17-01-23](https://user-images.githubusercontent.com/44745855/199756984-a2d66198-fc47-4dd2-bd6d-f238ee04408e.png)
 - you can do 
 ```ruby
def correct_name
      @nameable.correct_name.length > 10 ? @nameable.correct_name[0..9] : @nameable.correct_name
    end
```

2022-11-03 15:53 UTC, Elijahdre commented on decorators/trimmer_decorator.rb
> +  end
@DeliceLydia  Thanks!

2022-11-03 16:04 UTC, Whoistolu commented on decorators/trimmer_decorator.rb
> +  end
Well resolved 👍🏽

2022-11-03 16:05 UTC, Whoistolu approved these changes
### Hi @Elijahdre 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# STATUS: APPROVED 🟢
**Congratulations! 🎉** 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-03 16:07 UTC, merged

2022-11-03 16:07 UTC, Elijahdre commented on decorators/trimmer_decorator.rb
> +  end
Thanks man @Whoistolu

2022-11-03 16:07 UTC, Elijahdre commented on decorators/trimmer_decorator.rb
> +  end
Thanks man @Whoistolu

2023-01-15 09:40 UTC, Elijahdre commented
@Whoistolu Thank you mate 🙏